run:
  skip-dirs:
    - build
    - configs
    - deployments
    - docs
    - scripts
    - internal/core

linters-settings:
  golint:
    min-confidence: 0.8

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - golint
    - ineffassign
    - gosimple
    - gosec

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    - should have comment
    - should be of the form
    - should not use dot imports
    - which can be annoying to use
    # Binds to all network interfaces
    - G102
    # Errors unhandled
    - G104
    # file/folder Permission
    - G301
    - G302
    # Potential file inclusion via variable
    - G304
    # Deferring unsafe method like *os.File Close 
    - G307
    # Use of weak random number generator math/rand
    - G404
service:
  golangci-lint-version: 1.27.0 # use the fixed version to not introduce new linters unexpectedly

